services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: hpo_api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: hpo_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000