version: 2

sources:
- name: public
  database: hotel_performance
  schema: public
  tables:
  - name: fact_bookings
  - name: fact_aggregated
  - name: dim_date
  - name: dim_rooms
  - name: dim_hotels
