model:
  name: demand_forecaster
  target_column: rooms_sold

data:
  table: mtr_occupancy
  date_column: check_in_date

features:
  numerical:
  - rooms_available
  - adr

  nominal:
  - room_category
  - booking_channel
  - property_id
  - city

  ordinal: 
    category: [ Economy, Luxury ]

drop_cols:
- total_revenue
- rooms_sold 
